# Generated by Django 2.1.5 on 2019-02-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollNo',
            field=models.CharField(default=3301, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=8),
        ),
    ]
